### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by wdonet** [wdonet/nsquestions#15]
PP Session : 0.5hrs estimated

After going through the sign in button (http://localhost:8080/login) it redirects to Google, than it fails with the following message at the browser:

Error: redirect_uri_mismatch
Application: Nearsoft Questions
You can email the developer of this application at: imarban22@gmail.com
The redirect URI in the request: http://localhost:8080/auth/google did not match a registered redirect URI.

It seems it's not reaching up the NSQ app back.  How can we figure it out? for local envs?
Should we need a domain and a subdomain to redirect all requests to our local?

**Comment by imarban** [comment]
I set the redirect_uri in Google Developers Console as: http://localhost:**9000**/auth/google because I use to run NSQ in 9000 port. We have some solutions:

Configure in etc/hosts file a domain and set the redirect_uri property to this domain (Best approach)
Each developer has his own app at Google Console and set properties as he/she wants
Each developer uses 9000 (or any other) port for his/her local env.

**Comment by wdonet** [comment]
Could you elaborate more? I'm not following you at all. thanks

**Comment by imarban** [comment]
This is being closed changing the port in redirect_uri google app parameter to include the 8080 port instead 9000.
